# Generated by hand on 2021-12-15

from django.db import migrations


def sync_private_booleans(apps, schema_editor):
    Problem = apps.get_model('judge', 'Problem')
    Contest = apps.get_model('judge', 'Contest')
    db_alias = schema_editor.connection.alias

    for problem in Problem.objects.using(db_alias).all():
        problem.is_organization_private = problem.organizations.exists()
        problem.save()

    for contest in Contest.objects.using(db_alias).all():
        contest.is_private = contest.private_contestants.exists()
        contest.is_organization_private = contest.organization.exists()
        contest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0124_contest_show_short_display'),
    ]

    operations = [
        migrations.RunPython(sync_private_booleans, migrations.RunPython.noop),
    ]
